### ISSUE TITLE
Android Play Store button broke

### ISSUE THREAD

**Issue by Ginari** [WhisperSystems/whispersystems.org#101]
The Play Store button is broke. The image is missing.

**Tested in:** Chrome, Safari, Safari iOS

<img width="1211" alt="bildschirmfoto 2016-01-31 um 14 22 20" src="https://cloud.githubusercontent.com/assets/16880031/12702323/1bdf564c-c826-11e5-90cc-c92fbee790cd.png">

**Comment by liliakai** [comment]
dupe #100
