### ISSUE TITLE
No HTTPS on the support website

### ISSUE THREAD

**Issue by Lehmax** [WhisperSystems/whispersystems.org#108]
It's really strange that you'd use HTTPS on the regular site that has no forms on it, but don't implement it on the support site where people actually might enter sensitive data.

**Comment by mikijov** [comment]
Zendesk recently started offering to automatically manage SSL certificates to resolve precisely this problem. One of Whisper web admins has to log into Zendesk console, but now this should be just a click away. Please see [Introducing Zendesk provisioned SSL](https://support.zendesk.com/hc/en-us/articles/223222088-Introducing-Zendesk-provisioned-SSL).

**Comment by nrizzio** [comment]
This has been fixed.
