### ISSUE TITLE
Broken HTTPS on Textsecure service

### ISSUE THREAD

**Issue by swordbeta** [WhisperSystems/whispersystems.org#113]
Not sure if correct repository, but see: https://textsecure-service.whispersystems.org/

Same for: https://textsecure-service-ca.whispersystems.org/

**Comment by nrizzio** [comment]
All Signal clients (except the Desktop client) use certificate pinning.

See WhisperSystems/Signal-Android#5100 and Moxie's [comment](https://github.com/WhisperSystems/Signal-Android/issues/5100#issuecomment-173354859)
