### ISSUE TITLE
Is the Signal icon available as an SVG?

### ISSUE THREAD

**Issue by edent** [WhisperSystems/whispersystems.org#120]
The only copy of the icon I can find is on https://support.whispersystems.org/hc/en-us and it's a PNG.

Is there a vector version of the logo?

**Comment by liliakai** [comment]
I believe there are vectors embedded in this pdf: https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/Images.xcassets/logoSignal.imageset/logoSignal.pdf

**Comment by edent** [comment]
Indeed there is! Thanks :-)
