### ISSUE TITLE
website does not mention Signal

### ISSUE THREAD

**Issue by i7u** [WhisperSystems/whispersystems.org#40]
Update with photos & text of Signal-iOS.

Including a blurb about transparent interoperability (any Android phone with RedPhone can talk for free to any iPhone with Signal) would be useful.

**Comment by manhole11** [comment]
It still doesn't mention it...

**Comment by manhole11** [comment]
Signal got to version 2.0 and it STILL doesn't mention it..

**Comment by JavaJens** [comment]
@liliakai Any update on your patch?
