### ISSUE TITLE
Whispersystems.org uses insecure ciphers

### ISSUE THREAD

**Issue by piratenpanda** [WhisperSystems/whispersystems.org#65]
The SSLeuth addon for firefox rates the ssl ciphers used unsafe, please consider upgrading :)

![whispersystems](https://cloud.githubusercontent.com/assets/920721/5864748/9cfd83ca-a284-11e4-98ea-f6b0272b4398.png)

**Comment by moxie0** [comment]
for all that sensitive dynamic content on our website
