### ISSUE TITLE
Clearer, linkable app/product pages

### ISSUE THREAD

**Issue by aprescott** [WhisperSystems/whispersystems.org#79]
When I've wanted to link to a specific page for, say, TextSecure, in the past I've looked for a relevant blog post and used that, because there's no obvious way to send someone to the whispersystems.org website with a description of TextSecure, what it does, why it's worth using, etc.

The homepage has an "Apps" menu item:

![screen shot 2015-03-29 at 14 57 08](https://cloud.githubusercontent.com/assets/342081/6887140/42b43f16-d624-11e4-80ca-5f5c961b63e2.png)

Clicking that, though, scrolls down the page to a position that doesn't really give you anywhere else to go.

![screen shot 2015-03-29 at 14 57 20](https://cloud.githubusercontent.com/assets/342081/6887145/5b5a8606-d624-11e4-922f-a878eab68ea0.png)

A user may not even be aware that there's more to scroll down and read, but if they did, they wouldn't find more than a link to install the relevant app.

I think there's room for improvement here, by giving each app its own individual page and perhaps having a comparison-style page with a table showing each one and what it does.

**Comment by moxie0** [comment]
Thanks, we know. We have limited time and resources.

**Comment by aprescott** [comment]
Understandable. Is it worth leaving this open in case contributors want to take a shot at it, or is this something that requires lots of focus from the "owners" because it's a design issue?

**Comment by moxie0** [comment]
This requires a pretty substantial change, I don't think it's the kind of thing that will come in the form of a one-off PR.
