### ISSUE TITLE
/about page CSS is funky

### ISSUE THREAD

**Issue by davidxia** [WhisperSystems/whispersystems.org#80]
I noticed your about page's CSS is broken https://whispersystems.org/about/

I'm on mac 10.10.2 + chrome 42.0.2311.90

![screen shot 2015-04-29 at 12 53 15 am](https://cloud.githubusercontent.com/assets/480621/7384947/4945d81e-ee0a-11e4-8feb-5efb73b2febb.png)

**Comment by moxie0** [comment]
whoops, that's because that doesn't exist anymore. added a redirect.
