### ISSUE TITLE
"Join the Beta" button broken in Firefox

### ISSUE THREAD

**Issue by kyleconroy** [WhisperSystems/whispersystems.org#98]
Steps to reproduce:

1. Open Firefox
2. Visit https://whispersystems.org/blog/signal-desktop/
3. Click on "Join the beta" or "Join the beta today!"
4. Nothing happens (a a modal should pop up)

There are no errors in the console.

**Comment by big-r81** [comment]
Hi Kyle,

i cannot reproduce this. All works fine for me, see screenshot.

<img width="569" alt="joinbeta" src="https://cloud.githubusercontent.com/assets/9985963/12372945/c9055f0c-bc68-11e5-897b-9be6a5339d78.png">

**Comment by liliakai** [comment]
This was due to some shenanigans with the implementation of the form widget. Looks like it got worked out eventually.

**Comment by kyleconroy** [comment]
Thanks for getting it fixed!

**Comment by mammuth** [comment]
@kyleconroy you might close this issue, since it seems to be fixed in https://github.com/WhisperSystems/whispersystems.org/commit/870a86beed078e9c8f8d672dbdb0a9603f280a12?
